@place_name=warszawa
@ip=91.216.213.142


### Create new Company
POST http://localhost:5000/companies
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

{
  "name": "string",
  "brand": "string",
  "gov_id": "string",
  "gov_id_type": "string",
  "website": "string",
  "email": "mail@mail.pl",
  "phone": "string",
  "location": {
    "street_address": "string",
    "city": "Kraków",
    "state_province": "string",
    "postal_code": "string",
    "country": "pl",
    "located_in": "string",
    "type": "company",
    "lat": 52.237049,
    "lon": 21.017532
  }
}

### Create new main department (based on HQ adress)
POST http://0.0.0.0:5000/companies/department
accept: application/json
Content-Type: application/json

{
  "company_uuid": "972be3a2-1f1a-41a4-8130-aa8b0f783664",
  "name": "Kraków HQ"
}

### Create new Department from scratch

POST http://0.0.0.0:5000/companies/department
accept: application/json
Content-Type: application/json

{
  "company_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa1",
  "name": "string",
  "location": {
    "street_address": "string",
    "city": "string",
    "state_province": "string",
    "postal_code": "string",
    "country": "Pu",
    "located_in": "string",
    "type": "company",
    "lat": 0,
    "lon": 0
  }
}

###

