@place_name=warszawa
@ip=91.216.213.142


### Create new room
POST http://0.0.0.0:5000/rooms
accept: application/json
Content-Type: application/json

{
  "name": "Skarb Piratów",
  "company_uuid": "a64096f2-138c-45af-9966-04358914f831",
  "department_uuid": "8c844511-3d34-45e4-a6dd-2d0bd7bc63fc",
  "price_from": 160,
  "game_duration": 60,
  "players_min": 2,
  "players_max": 4,
  "reservation_url": "https://lockandroll.pl/booking/1/",
  "lm_id": "room-706",
  "mt_id": null,
  "translation": [
    {
      "lang": "pl",
      "title": "Skarb Piratów",
      "lead": "Odzyskaj medalion Rudobrodego z pirackiej tawerny pełnej zagadek!",
      "description": "Rudobrody, słynny wilk morski, stracił swój najcenniejszy skarb – tajemniczy medalion, który miał wręczyć ukochanej. Wszystko przez słabość do hazardu i rumu, która zawiodła go do pirackiej tawerny pełnej kart, głośnych śmiechów i zgubnych zakładów. Teraz, zrozpaczony i bezradny, zwraca się do Was – jedynych, którzy mogą uratować jego honor i odzyskać to, co przepadło. Piracka tawerna w sercu Krakowa to miejsce pełne tajemnic, podstępnych pułapek i zagadek, które przetestują Wasz spryt i odwagę. Każdy krok naprzód odkrywa kolejne sekrety, a stawka rośnie z każdą chwilą. Czy zdołacie odzyskać skarb i pokonać wyzwania tego niezwykłego escape roomu? Rudobrody pokłada w Was nadzieję – nie zawiedźcie go!"
    },
    {
      "lang": "en",
      "title": "Pirates' Treasure",
      "lead": "Recover Rudobrody's medallion from a pirate tavern full of puzzles!",
      "description": "Rudobrody, a famous sea wolf, lost his most precious treasure – a mysterious medallion he intended to give to his beloved. All because of his weakness for gambling and rum, which led him to a pirate tavern filled with cards, loud laughter, and risky bets. Now, desperate and helpless, he turns to you – the only ones who can restore his honor and reclaim what was lost. The pirate tavern in the heart of Krakow is a place full of mysteries, cunning traps, and puzzles that will test your wit and courage. Every step forward reveals more secrets, and the stakes grow higher with every passing moment. Can you retrieve the treasure and overcome the challenges of this extraordinary escape room? Rudobrody is counting on you – don’t let him down!"
    }
  ]
}

### Create new room - full template
POST http://0.0.0.0:5000/rooms
accept: application/json
Content-Type: application/json

{
  "name": "string",
  "company_uuid": "a64096f2-138c-45af-9966-04358914f831",
  "department_uuid": "8c844511-3d34-45e4-a6dd-2d0bd7bc63fc",
  "price_from": 0,
  "game_duration": 0,
  "players_min": 0,
  "players_max": 0,
  "reservation_url": "string",
  "lm_id": "string",
  "mt_id": "string",
  "location": {
    "street_address": "string",
    "city": "string",
    "state_province": "string",
    "postal_code": "string",
    "country": "PL",
    "located_in": "string",
    "type": "company",
    "lat": 0,
    "lon": 0
  },
  "translation": {
    "lang": "pl",
    "title": "string",
    "lead": "string",
    "description": "string"
  }
}


