@place_name=warszawa
@ip=91.216.213.142


### Create new Company
POST http://localhost:5000/companies
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

{
  "name": "string",
  "brand": "string",
  "gov_id": "string",
  "gov_id_type": "string",
  "website": "string",
  "email": "string",
  "phone": "string",
  "location": {
    "street_address": "string",
    "city": "string",
    "state_province": "string",
    "postal_code": "string",
    "country": "Ff",
    "located_in": "string",
    "type": "company",
    "lat": 0,
    "lon": 0
  }
}
